const HU_DICT = {
  // We're Not Gonna Take It
  "We're Not Gonna Take It":"Nem tűrjük tovább",
  "No, we ain't gonna take it.":"Nem, nem tűrjük tovább.",
  "We're not gonna take it anymore.":"Nem tűrjük tovább",
  "We've got the right to choose and there ain't no way we'll lose it.":"Jogunk van a választáshoz, és semmiképpen sem fogjuk elveszíteni.",
  
  // *** How do I spot the International Space Station? ***
  "How do I spot the International Space Station?":"Hogyan láthatom meg a Nemzetközi Űrállomást?",
  "Time is when the sighting opportunity will begin in the local time zone of a user’s preferred location.":"Ez az az időpont, amikor a megfigyelési lehetőség kezdetét veszi a felhasználó által választott helyszín helyi időzónája szerint.",
  "All International Space Station sightings will occur within a few hours before or after sunrise or sunset.":"A Nemzetközi Űrállomás észlelésére minden napkelte vagy napnyugta előtt, illetve után néhány órán belül kerül sor.",
  "This is the optimum viewing period as the Sun reflects off the space station and contrasts against the darker sky.":"Ez az optimális megfigyelési időszak, mivel a Nap fénye visszaverődik az űrállomásról, amely így élesen kirajzolódik a hátterében sötétebb égbolton.",
  "Above the Horizon is the amount of time the space station is visible before crossing back below the Earth’s horizon.":"Az „Above the Horizon” (horizont felett) az az időtartam, ameddig az űrállomás látható, mielőtt újra a Föld horizontja alá kerülne.",
  
  // TAGMONDATOK ****
  "All International Space Station sightings will occur within":"A Nemzetközi Űrállomás észlelésére",
  "a few hours before or after sunrise or sunset.":"minden napkelte vagy napnyugta előtt, illetve után néhány órán belül kerül sor.",
  "This is the optimum viewing period":"Ez az optimális megfigyelési időszak",
  "as the Sun reflects off the space station ":"mivel a Nap fénye visszaverődik az űrállomásról,",
  "the Sun reflects off the space station and contrasts against the darker sky.":"amely így élesen kirajzolódik a hátterében sötétebb égbolton.",
  "Above the Horizon is the amount of time":"Az „Above the Horizon” (horizont felett) az az időtartam,",
  "the space station is visible before crossing back below the Earth’s horizon.":"ameddig az űrállomás látható, mielőtt újra a Föld horizontja alá kerülne.",
  
  
  
  //**********The Hunt for H.G. Growmore *****
  "The Hunt for H G Growmore.":"H.G. Growmore nyomában",
  "This is awful, muttered Isabella in a low, wobbly voice.":"– Ez borzalmas mormogta Isabella halk, remegő hangon.",
  "Behind her on the only bed in the room Kay did not react.":"Mögötte, a szoba egyetlen ágyán Kay nem reagált.",
  "The half-length mirror in front of Isabella showed him clearl, lying on her pillows, absentmindedly rubbing his upper lip with a finger.":"Az Isabella előtti félalakos tükör tisztán mutatta őt, amint a párnáin fekve, szétszórtan az ujjával dörzsölgette a felső ajkát.",
  "His eyes did not leave the page facing him - a funny-looking picture of some sort of aliens was on the book cover.":"Nem vette le a szemét az előtte lévő oldalról; a könyvborítón valamilyen földönkívülieket ábrázoló, mókás kinézetű kép volt.",
  "Aliens Humph":"Földönkívüliek. Hmph!",
  "“It’s really, really dreadful,” she added hopefully, sneaking a look at him over one shoulder.":"– Ez igazán, de igazán borzalmastette hozzá reménykedve, miközben félvállról odapillantott rá.",
  "What on earth was so fascinating about visitors from another world?":"Mi a csudáért voltak annyira lenyűgözőek a más világból érkező látogatók?",
  "She opined, that Bella in JSS 3 that nose of hers looks like it always wants to tell everyone what to do and how to do it too!":"Úgy vélte -Az a Bella a JSS 3-ból... az orra olyan, mintha folyton meg akarná mondani mindenkinek, mit tegyensőt, még azt is, hogyan!",
  "Right at the moment, however, Isabella’s nose was the last thing on her mind.":"Ebben a pillanatban azonban Isabella orra volt az utolsó dolog, amire gondolt.",
  "Even his eyes didn’t blink now":"Még a szeme sem rezzent meg most.",
  "fascinating about visitors from another world":"lenyűgözőek a más világból érkező látogatók?",
  "what about people from this planet":"Mi a helyzet az e bolygóról származó emberekkel?",
  "like his kid sister for instance":"Például a húga.",
  "The book fell from his hands.":"Kiesett a könyv a kezéből.",
  "smacking a palm on the mirror for good measure":"biztonság kedvéért tenyérrel rácsapva a tükörre",
  "showed":"mutatott, megmutatta","Isabella yelled, smacking a palm on the mirror for good measure, making Kay jump two feet off the bed":"Isabella felkiáltott, és nyomatékosításképpen tenyérrel rácsapott a tükörre, amitől Kay majdnem kiugrott a bőréből.",
  "the smile vanished like her pocket money halfway through the month":"A mosoly úgy tűnt el, mint a zsebpénze a hónap közepén.",
  "i don't believe this":"Ezt nem hiszem el!",
  "just unthinkable!":"Egyszerűen elképzelhetetlen!",
  "she moaned staring with wide eyes at her reflection in the mirror":"felsóhajtott, miközben tágra nyílt szemmel bámulta a tükörben látható tükörképét.",
  "the image that stared back eyes alarmed long wispy hair all awry was that of a pubescent female skin like the sunset of a day spent on the beach much too tall for her age with a perky slightly upturned nose adorning a decidedly pretty face":"A visszanéző arcriadt szemekkel és kócos vékony szálú hajjalegy serdülőkorú lányé volt bőre a tengerparton töltött naplementét idézte termete korához képest túl magas volt csinos arcát pedig pisze kissé felfelé kunkorodó orr tette bájossá.",
  "Mommy said Isabella’s nose was her most visible facial feature; walking nose first, she termed it, shaking her head with indulgent pride.":"Anya azt mondta, Isabella orra a legszembetűnőbb vonása; „orrát előretolva közlekedik”így jellemezte, miközben elnéző büszkeséggel csóválta a fejét.",
  "darkness":"sötétség","he gaped at isabella in astonishment quite speechless":"Ámulva bámult Isabellára, teljesen szótlanul.",
  "there much better isabella started to smile then caught a glimpse of herself in the mirror":"Ott, sokkal jobban, Isabella mosolyogni kezdett, majd megpillantotta magát a tükörben.","kay seemed carved from stone":"Kay mintha kőből lett volna faragva.","even his eyes didnt blink now":"Még a szeme sem rezzent meg most.",
  "its really really dreadful":"Ez tényleg nagyon szörnyű","she added hopefully sneaking a look at him over one shoulder":"– tette hozzá reménykedve, miközben válla fölött lopva rápillantott.",
  "Teacher Ngozi at school wasn’t such a fan, though.":"Az iskolában azonban Ngozi tanárnő nem volt annyira oda érte.",
  "And what could she do?":"És mit tehetett volna?",
  "The funny thing was, this was absolutely the worst day to feel awful about anything.":"Az volt az egészben a vicces, hogy ez volt a lehető legrosszabb nap arra, hogy az ember bármi miatt is pocsékul érezze magát.",
  "To start with, outside, the July sun blazed happily on a world filled with singing birds and happy, playing children.":"Először is, kint a júliusi nap boldogan tűzött egy világra, amely tele éneklő madarakkal és boldog, játszó gyerekekkel.",
	 "Up and down the street in this residential Estate in Kaduna City, one could almost touch the palpable euphoria in the air.":"Kaduna városának ebben a lakónegyedében az utcán szinte kézzel fogható volt a levegőben vibráló eufória.","And with reason too.":"És nem is ok nélkül.",
	 "This was the first day of the long holidays, the long vac as school kids all over the country called it.":"Ez volt a hosszú szünet első napjaahogy az ország minden táján a diákok nevezték: a „nagy szünet”.",
	 "They were the height of every Nigerian Kid’s year, looked forward to with ever-mounting excitement as they slowly approached.":"Minden nigériai gyerek számára ezek jelentették az év csúcspontját, amelyek közeledtével egyre fokozódó izgalommal telt meg a szívük.",
	 "7 glorious school-free weeks!":"7 csodálatos, iskolamentes hét!",
	 "With absolutely nothing or everything to do, depending on one’s personal energy level.":"Amikor az embernek vagy semmi dolga sincsvagy épp ellenkezőleg: rengeteg –, attól függően, mennyi energia lakozik benne.",
	"The air fairly hummed with plans being made, even if they were just thoughts of lazing around the house, bedroom, beach, garden, poolside, or stream, watching tiktoks, glued in front of a tv screen, with a fav book or movie, or absolutely nothing at all.":"A levegő szinte vibrált a készülő tervektőlmég ha azok csupán arról szóltak is, hogy az ember otthon, a hálószobában, a strandon, a kertben, a medence partján vagy a patak mellett henyéljen; TikTok-videókat nézzen, a tévé képernyője elé szegeződjön, kedvenc könyvét vagy filmjét élvezze, vagy éppenséggel ne csináljon semmit a világon.",
 "Whatever chilled your ice cream.":"Bármi is hűtötte a fagylaltot.",
 "Kids everywhere were in holiday heaven.":"A gyerekek mindenütt az ünnepi boldogság csúcsán érezték magukat.",
 "However, Isabella was not thinking about the holidays either.":"Isabella azonban nem az ünnepekre gondolt.",
 "She gasped as she ran a long comb through her hair once more.":"Felszisszent, miközben még egyszer végighúzta fésűjét a hosszú haján.",
 "Several fine strands came away with the comb.":"Néhány vékony hajszál kijött a fésűvel.",
 "Others floated softly to the floor.":"Néhány lágyan a padlóra hullott.",
 "Now she groaned, staggering back to flop into a pretty daffodil-covered armchair by the window.":"Ekkor felnyögött, és tántorogva visszahanyatlott az ablak melletti, csinos, nárc-mintás karosszékbe.",
 "The bedroom was Barbie recommended pink, violet, and white.":"A hálószobában a Barbie által ajánlott rózsaszín, ibolyakék és fehér színek domináltak.",
 "Pictures of animated heroines, ballet dancers, singers, and actresses decorated the walls.":"Animációs filmek hősnőiről, balett-táncosokról, énekesnőkről és színésznőkről készült képek díszítették a falakat.",
 
 // *** Rescue pup ***
  
  "On the far edge of town in the thick of the woods curved a long winding road where a tiny house stood.":"A város szélétől távol, az erdő sűrűjében kanyargott egy hosszú, tekervényes út, amely mellett egy apró ház állt.",
  "All alone in that house sat a pup who was sad.":"Abban a házban magányosan ült egy szomorú kiskutya.",
  "There was no one to play with no friends to be had.":"Nem volt kivel játszania, nem voltak barátai.",
  "While he waited and watched for the door to unlock, it grew dark in the house . . .":"Miközben várakozott, és azt figyelte, mikor nyílik ki az ajtó, besötétedett házban.",
  "Then he heard a loud knock!":"Aztán egy hangos... KOPOGÁST hallott!",
  "There was no one outside, just the wicked old winds that ripped through the trees and tore down the limbs!":"Kint nem volt senki, csak a gonosz, vén szelek, amelyek végigsöpörtek a fákon, és letördelték az ágakat!",
  "As dark gloomy clouds blew over the moon, lightning bolts flashed and thunder ka-BOOMED!":"Ahogy sötét, komor felhők úsztak a hold elé, villámok cikáztak, a mennydörgés pedig hatalmas dörrenéssel tört ki.",
  "The little dog dashed up the stairs, down the hall, and he shook all night long from the sounds of the squall.":"A kiskutya felrohant a lépcsőn, végigszaladt a folyosón, és egész éjjel remegett a vihar zajától.",
  "By morning the storm was over and done.":"Reggelre a vihar véget ért.",
  "The rain cleared up and out came the sun.":"Elállt az eső, és kisütött a nap.",
  "The puppy was hungry.":"A kiskutya éhes volt.",
  "He looked all around for water and food.":"Körülnézett víz és élelem után.",
  "There was none to be found.":"Nem talált semmit.",
  "Soon day became night and then daytime once more, but no one came home to unlock the front door.":"Hamarosan nappalból éjszaka, majd újra nappal lett, ám senki sem jött haza, hogy kinyissa a bejárati ajtót.",
  "So he howled and he whimpered in terrible fear that no one would rescue him — no one would hear!":"Így hát üvöltött és nyüszített, szörnyű félelem gyötörte, hogy senki sem menti megsenki sem hallja meg!",
  "This poor lonesome pup couldn't wait any more, so he clawed at the windows and pawed on the doors.":"Ez a szegény, magányos kiskutya már nem bírt tovább várni, ezért az ablakokat kaparta, az ajtókat pedig a mancsával döngette.",
  "He pushed on a screen, scratched a hole ‘til it grew.":"Megnyomott egy rácsot, és addig kaparta, míg lyuk nem keletkezett rajta, és az nagyobbra nem nőtt.",
  "Then he twisted and shoved and squeezed his way through.":"Aztán csavarodva, lökdösődve és préselődve átjutott.",
  "He was free now at last as he crept very slow through the woods and the darkness not sure where to go.":"Végre kiszabadult, miközben nagyon lassan lopakodott át a sötét erdőn, és a bizonytal volt afelől, merre is menjen.",
  "Coming out of the trees, he found danger too soon.":"Ahogy kiért a fák közül, hamar veszélybe került.",
  "He was chased down the path by a mean old raccoon.":"Egy gonosz öreg mosómedve kergette végig az ösvényen.",
  "As he ran through a field, there were sharp prickly burrs that stuck to his toes, and his legs, and his fur.":"Ahogy átfutott a mezőn, éles, szúrós bogáncsok tapadtak a lábujjaira, a lábára és a bundájára.",
  "He was hurt once again on his way into town when he stepped on some glass all scattered around.":"A városba menet ismét megsérült, amikor rálépett valami összetört pohárra.",
  "He kept looking for someone, a friend who might care, but instead he heard Scram!":"Folyamatosan keresett valakitegy barátot, akit talán érdekelne a dolog –, ám ehelyett csak annyit hallott: „Tűnés!”",
  "So he ran far from there.":"Így hát messzire futott onnan.",
  "Then he faced the worst danger of all on that night — A highway!":"Aztán azon az éjszakán szembe kellett néznie a legfőbb veszéllyel: egy országúttal!",
  "Fast cars!":"Gyors autók!",
  "Headlights blinding his sight!":"Fényszórók vakítják el!",
  "He stopped.":"Megállt",
  "Then he turned.":"Aztán megfordult.",
  "When he started to go, a car blared its horn, tires screeched, and — OH, NO!":"Amikor elindult, egy autó dudált, a gumik felsikoltottak, ésÓ, ne!",
  "The car quickly stopped; someone opened the door.":"Az autó hirtelen megállt; valaki kinyitotta az ajtót.",
  "The pup froze!":"A kölyök megdermedt!",
  "Could he possibly take anymore?":"Vajon képes lenne még többet elviselni?",
  "Then a lady stepped out.":"Aztán egy hölgy lépett ki.",
  "Little Buddy! she cried.":"Kis pajtás!kiáltotta.",
  "Are you lost?":"Eltévedtél?", "Are you hurt?":"Megsérültél?", "Let me get you inside!":"Hadd vigyelek be!",
  "He was glad to be rescued and happy to find a friend who could help him — someone who was kind.":"Örült, hogy megmentették, és boldog volt, hogy talált egy barátot, aki segíthetett nekivalakit, aki kedves volt.",
  "The little pup loved his first ride in a car 'til the lady said, Buddy, get up!":"A kis kutyus imádta az első autózását, egészen addig, amíg a hölgy azt nem mondta: „Pajtás, kelj fel!”",
  "Here we are!":"Megérkeztünk!",


  // *** rescue kitty fordítás ***
  "on a warm summer night right outside my backdoor shadows passed green eyes flashed":"Egy meleg nyári éjszakán, közvetlenül a hátsó ajtóm előtt árnyak suhantak el, és zöld szemek villantak fel.",
  "On a warm summer night":"Egy meleg nyári éjszakán",
  "right outside my backdoor":"közvetlenül a hátsó ajtóm előtt",
  "shadows passed":"árnyak suhantak el",
  "Then I saw them no more.":"Aztán többé nem láttam őket.",
  "so I ran to the bushes":"Így hát a bokrokhoz rohantam,",
  "and yanked them apart":"és szét rángattam az ágakat,",
  "but whatever it was shot off like a dart.":"de bármi is volt az, nyílvesszőként lőtt ki onnan.",
  "had i seen a red fox a possom an owl":"Vajon vörös rókát, oposszumot, baglyot láttam?",
  "maybe something nocturnal was out on the prowl":"Talán valami éjszakai állat ólálkodott a közelben?",
  "maybe something":"Talán valami",
  "nocturnal was out on the prowl":"éjszakai állat ólálkodott a közelben?",
  "green eyes flashed":"és zöld szemek villantak fel.",
  "Mom called from the house, ”Luis, it is late!":"Anya hívott a házból: „Luis, késő van!”",
  "Mom called from the house":"Anya hívott a házból:",
  "Luis, it is late!":"Luis, késő van!",
  "The mystery creature":"A rejtélyes lénynek",
  "would just have to wait":"várnia kellett",
  "When the sun poked its head on the very next day":"Amikor másnap reggel előbukkant a nap",
  "I flew out of bed to run outside and play":"kiugrottam az ágyból, hogy kiszaladjak játszani",
  "The mystery creature would just have to wait.":"A rejtélyes lénynek várnia kellett.", 
  "When the sun poked its head on the very next day, I flew out of bed to run outside and play!":"Amikor másnap reggel előbukkant a nap, kiugrottam az ágyból, hogy kiszaladjak játszani.",
  "I remembered the eyes,":"Emlékeztem a szemekre,",
  "so I gazed all around":"ezért körbepillantottam",
  "Sure enough":"És valóban",
  "on the woodpile a cat hunkered down":"a farakáson egy macska kuporgott",
  "I called, Here Kitty Kitty,":"Hívogattam: „Cic-cic!",
  "but with one graceful push":"ám egyetlen kecses mozdulattal elrugaszkodott a magasabb helyről",
  "she leaped from her perch and was lost in the bush":"és eltűnt a bokrok között",
  
  
  
  "I remembered the eyes, so I gazed all around.":"Emlékeztem a szemekre, ezért körbepillantottam.",
  "Sure enough on the woodpile a cat hunkered down.":"És valóban, a farakáson egy macska kuporgott.",
  "I gasped!":"Felevegő után kaptam!",
  "Then I froze.":"Aztán megdermedtem.",
  "We locked eyes, and I stared.":"Összefonódott a tekintetünk, és én meredten bámultam.",
  "I could see she was feeling uneasy and scared.":"Láttam rajta, hogy nyugtalan és fél.",
  "I called, Here Kitty Kitty, but with one graceful push, she leaped from her perch and was lost in the bush.":"Hívogattam: „Cic-cic!”, ám egyetlen kecses mozdulattal elrugaszkodott a magasabb helyről, és eltűnt a bokrok között.",
  "I hunted and hunted; no cat was in sight.":"Kerestem, kerestem; sehol sem látszott macska.",
  "I hoped she'd come back, and I thought she just might.":"Reméltem, hogy visszajön, és úgy gondoltam, talán meg is teszi.",
  "She surprised me again curled up on the mat.":"Ismét meglepett, ahogy a szőnyegen összegömbölyödve feküdt.",
  "Oh, I had to tell Mom about Cally-co cat.":"Ó, mesélnem kellett anyunak a háromszínű macskáról.",
  "Mom said, This cat is frail; she is hungry and thin.":"Anya azt mondta: „Ez a macska gyenge; éhes és sovány.”",
  "I'm not sure where she came from, or where she has been.":"Nem vagyok biztos benne, honnan jött, vagy hol járt.",
  "But it's time someone cared, for she needs a good meal.":"De ideje, hogy valaki törődjön vele, mert szüksége van egy jó ételre.",
  "With those scratches and cuts, she could use time to heal.":"Azokkal a karcolásokkal és vágásokkal ráférne egy kis idő a gyógyulásra.",
  "So we filled up a pan with fresh milk and chow.":"Így hát megtöltöttünk egy tálat friss tejjel és eleséggel.",
  "After gulping it down, she sang friendly meows.":"Miután gyorsan lenyelte, barátságos nyávogásba kezdett.",
  "We invited her in, but she lingered outside.":"Hívtuk be, de ő kint maradt.",
  "We wondered if Cally had something to hide.":"Azon tűnődtünk, vajon Cally rejteget-e valamit.",
  
  
  
  "Right at the moment, however, Isabella’s nose was the last thing on her mind":"Ebben a pillanatban azonban Isabella orra volt az utolsó dolog, amire gondolt.",
  "Are you on the phone":"Telefonálsz?","She really couldn’t bear it":"Egyszerűen nem tudta elviselni.",
  "It was a totally awful, awful thing to be happening!":"Egészen szörnyű, szörnyű dolog volt ez!",
  "So I ran to the bushes and yanked them apart, but whatever it was shot off like a dart.":"Így hát a bokrokhoz rohantam, és széttéptem az ágakat, de bármi is volt az, nyílvesszőként lőtt ki onnan.",
  
"In the late afternoon, winds blew in from the West.":"Késő délután nyugat felől feltámadt a szél.",
"Raindrops pelted the ground.":"Esőcseppek doboltak a földön.",
"Cally acted distressed!":"Cally zaklatottnak tűnt!",
"As she paced on the porch, she peered over the wall, reaching down with her paw toward what looked like a ball.":"Miközben a verandán járkált, átpillantott a falon, és mancsával lefelé nyúlt valami felé, ami labdának tűnt.",
"Branches twisted and bent.":"Az ágak csavarodtak és hajlottak.",
"Oak trees whipped overhead.":"Tölgyfák csapkodtak a fej fölött.",
"As the dark sky flashed white, my heart filled with dread!":"Ahogy a sötét égbolt fehéren felvillant, szívemet elfogta a rettegés!",
"Tiny kittens!":"Apró kiscicák!",
"With shrill desperate cries, they clung to each other beneath stormy skies.":"Éles, kétségbeesett kiáltásokkal kapaszkodtak egymásba a viharos égbolt alatt.",
"Mom! I yelled pointing at kittens below.":"Anya! -Kiabáltam, miközben a lent lévő kiscicákra mutattam.",
"Cally's trying to save them.":"Cally próbálja megmenteni őket.",
"Let's help her.":"Segítsünk neki.","Let's go!":"Menjünk!",
"So we put on our coats; down the porch steps we flew, and we battled the storm scooping kittens up, too.":"Így hát felvettük a kabátunkat; lementünk a veranda lépcsőjén, és megküzdöttünk a viharral és a felkapaszkodó kiscicákkal.",
"Then we hurried inside holding all of them tight.":"Aztán sietve bementünk, miközben szorosan fogtuk mindet.",
"Cally trotted behind us — her kittens in sight!":"Cally ügetett mögöttünka cicái is látszottak!",
"She counted each baby now safe from all harm, then frantically ran to the door in alarm!":"Megszámolta a minden bajtól immár biztonságban lévő kicsiket, majd rémülten, fejvesztve rohant az ajtóhoz!",
"Cally leaped off the porch swiftly searching around beneath boxwoods and hostas and finally found.":"Cally leugrott a verandáról, fürgén körülnézett a puszpángbokrok és az árnyékliliomok alatt, és végül rátalált.",
"ONE kitten we'd left all alone in the rain. He was stuck in a thorn bush and cried out in pain!":"Egyetlen kiscicát hagytunk magára az esőben. Tövisbokorba szorult, és fájdalmában sírt!",
"We carefully freed him and calmed him down, too.":"Óvatosan kiszabadítottuk, és megnyugtattuk.",
"Soon he settled right in with the rest of his crew.":"Hamar beilleszkedett a többi kölyök közé.",
"Cally's family at last — safe and sound not a peep bellies full, cozied up, snug and warm, fast asleep.":"Cally családja végreépségben és egészségben, teljes csendben, tele hassal, kényelembe helyezve magát, melegen és otthonosan, mély álomba merülve.",
"The weeks flew by quickly.":"Gyorsan múltak a hetek.","The kittens had grown.":"A kiscicák megnőttek",
"Time to visit the vet.":"Ideje elmenni az állatorvoshoz.","Time to find them new homes.":"Ideje új otthont találni nekik.",
"Cally saw the vet, too for a check up and spay.":"Cally is vittük az állatorvoshoz vizsgálatra és ivartalanításra.",
"Her new home was with me, and forever she'd stay!":"Nálam lett az új otthona, és örökre itt is maradt!",
	// rövid mondatok ***
"It’s nice to meet you!":"Örülök, hogy találkozunk!",
"My pleasure.":"Örömömre szolgál. (Én is örülök.)",
"How are you doing?":"Hogy vagy?",
"I’m fine, thanks.":"Jól, köszi.",
"Brilliant, thank you.":"Nagyon jól, köszönöm.",
"I’ve been better, thanks.":"Voltam már jobban is.",
"And you?":"És te?",
"How are you?":"Hogy vagy?",
"Are you okay?":"Jól vagy?",
"Is everything all right?":"Minden rendben?",
"What time is it?":"Mennyi az idő?",
"Can you tell me what time it is, please?":"Meg tudnád mondani, mennyi az idő?",
"It’s half past seven.":"Fél nyolc van.",
"It’s quarter to three.":"Háromnegyed három van.",
"It’s quarter past five.":"Negyed hat van.",
"It’s ten fifteen.":"Tíz óra tizenöt perc van.",
"Let’s meet at five o’clock.":"Találkozzunk öt órakor.",
"When are you free?":"Mikor érsz rá?",
"I would be happy to meet you at your convenience.":"Örömmel találkoznék veled, amikor neked megfelel.",
"Are you free to meet this week?":"Ráérsz találkozni ezen a héten?",
"Do you have some time now?":"Van most egy kis időd?",
"Excuse me, can you help me?":"Elnézést, tudnál segíteni nekem?",
"Could you help me?":"Tudnál segíteni?",
"Would you, please, help me?":"Tudnál, kérlek, segíteni nekem?",
"Of course":"Természetesen.",
"How can I help you?":"Hogyan segíthetek?",
"I’d be happy to help you.":"Örömmel segítek neked.",
"Could you tell me where the … is, please?":"Meg tudnád mondani, kérlek, hol van a …?",
"How can I get to …?":"Hogyan jutok el a …-hoz?",
"Go straight ahead.":"Menj egyenesen.",
"Turn left.":"Fordulj balra.",
"Turn right.":"Fordulj jobbra.",
"Cross the street.":"Menj át az úton.",
"Take the bus.":"Szállj fel a buszra.",
"Take the underground.":"Szállj fel a metróra.",
"Take the tram.":"Szállj fel a villamosra.",
"It’s on the corner of Smith and Lodge street.":"A Smith és a Lodge utca sarkán van.",
"I would be happy to meet you at your convenience.":"Örömmel találkoznék veled, amikor neked megfelel.",
"Do you know Matilda?":"Ismered Matildát?",
"I knew that.":"Tudtam. / Ezt tudtam.",

//Személyes névmások
"I":"– én",
"You":"– te",
"He":"– ő (férfi)",
"She":"– ő (nő)",
"It":"– az (dolog, állat)",
"We":"– mi",
"They":"– ők",
//Birtokos névmások (Possessive Pronouns)

"My":"– az én …-m",
"Your":"– a te …-d",
"His":"az ő …-ja (férfi)",
"Her":"az ő …-ja (nő)",
"Its":"az ő …-ja (dolog, állat)",
"Our":"a mi …-nk",
"Their":"az ő …-juk",
//Kérdőszavak (Question Words)
"What":"mi, mit",
"Who":"ki",
"Where":"– hol",
"When":"mikor",
"Why":"miért",
"How":"hogyan",
"Which":"melyik",
"Whose":"kié",
"Whom":"kit, kinek",
"How many":"hány, mennyi, hány darab",
//Mindennapi tárgyak (Everyday Objects)

"Book.":"könyv",
"Table.":"asztal",
"Phone":"telefon",
"Car.":"autó",
"House":"ház",
"Chair":"szék",
"Window":"ablak",
"Door":"ajtó",
"Bag":"táska",
"Key":"kulcs",
"Pen":"– toll",
"Computer":"számítógép",
"TV":"televízió",
"Bottle":"üveg",
"Cup":"csésze",

//Helyek és irányok (Places and Directions)
"Here":"itt",
"There":"ott",
"Home":"otthon",
"Away":"távol",
"In":"benne",
"On":"rajta",
"Under":"alatta",
"Over":"fölötte",
"Between":"között",
"Next to":"mellette",
"Behind":"mögött",
"Above":"fölötte",
"Below":"alatta",
"Near":"közel",
"Far":"messze",
//Melléknevek (Adjectives)

"Good":"jó, szép, kitűnő",
"New":"új",
"First":"első",
"Last":"utolsó",
"Long":"hosszú",
"Great":"nagyszerű",
"Little":"kicsi",
"Own":"saját",
"Other":"más",
"Old":"régi, öreg",
"Right":"helyes, jobb (irány)",
"Big":"nagy",
"High":"magas",
"Different":"különböző",
"Small":"kicsi",
"Large":"nagy",
"Next":"következő",
"Early":"korai",
"Young":"fiatal",
"Important":"fontos",
"Few":"néhány",
"Public":"nyilvános",
"Bad":"rossz",
"Same":"ugyanaz",
"Able":"képes valamire",
// dő kifejezése (Time Expressions)

"Time":"idő",
"Year":"év",
"Day":"nap",
"Week":"hét",
"Month":"hónap",
"Today":"ma",
"Tomorrow":"holnap",
"Now":"most",
"Yesterday":"tegnap",
"Night":"éjszaka",
"Morning":"reggel",
"Evening":"este",
"Hour":"óra",
"Minute":"perc",
"Second":"másodperc",
// *** BEST FRIENDS ***
 "Zindzi and Tim Tam were best friends.":"Zindzi és Tim Tam legjobb barátok voltak.",
 "They did everything together.":"Mindent együtt csináltak.",
 "Do you want to play dress-up? -asked Oswin":"Szeretnél beöltöztetőst játszani -kérdezte Oswin",
 "Do you want to play dress-up?":"Szeretnél beöltöztetőst játszani?",
 "-asked Oswin":"-kérdezte Oswin",
 "No thank you, said Zindzi.":"Nem, köszönöm – mondta Zindzi.",
 "I’ll play dress-up with Tim Tam.":"Beöltöztetőst játszom majd Tim Tammal.",
 "Do you want to do a puzzle with me? -asked Kaya.":"– Szeretnél kirakózni velem – kérdezte Kaya.",
 "Do you want to do a puzzle with me?":"– Szeretnél kirakózni velem?",
 " -asked Kaya.":"– kérdezte Kaya.",
 "No thank you, -said Zindzi.":"– Nem, köszönöm – mondta Zindzi.",
 "I like doing puzzles with Tim Tam.":"Tim Tammal szeretek kirakózni.",
 "Do you want to join our scooter race? -asked The Twins.":"– Szeretnétek csatlakozni a rollerversenyünkhöz – kérdezték az ikrek.",
 "Do you want to join our scooter race?":"– Szeretnétek csatlakozni a rollerversenyünkhöz?",
 "-asked The Twins.":"– kérdezték az ikrek.",
 "No thank you, -said Zindzi.":"– Nem, köszönöm – mondta Zindzi.",
 "I’ll race with Tim Tam.":"Majd Tim Tammal versenyzek.",
 "One day, Tim Tam didn’t come to school.":"Egy nap Tim Tam nem jött iskolába.",
 "Tim Tam is sick, -said Teacher.":"– Tim Tam beteg – mondta a tanár.",
 "Why don’t you play with your other friends, Zindzi?":"Miért nem játszol a többi barátoddal, Zindzi?",
 "Oswin was making a -Get Well Soon- card for Tim Tam.":"Oswin éppen „Jobbulást!”-kártyát készített Tim Tamnak.",
 "But… Tim Tam is my best friend, said Zindzi.":"– De… Tim Tam a legjobb barátom – mondta Zindzi.",
 "You can help me, -said Oswin.":"– Segíthetsz nekem – mondta Oswin.",
 "Dip dip, -dab dab Dip dip, dab dab- -said Zindzi.":"Márt-márt, – paskol-paskol, márt-márt, paskol-paskol – mondta Zindzi.",
 "When the card was done, Oswin and Zindzi played dress-up.":"Amikor elkészült a kártya, Oswin és Zindzi jelmezes játékba kezdtek.",
 "The next day, they played hopscotch with Kaya.":"Másnap ugróiskoláztak Kayával.",
 "The day after that, the three of them rode scooters with the Twins.":"Másnap hárman rollereztek az ikrekkel.",
 "On Monday, Tim Tam came back to school.":"Hétfőn Tim Tam visszatér az iskolába.",
 "Let’s go read a book with Oswin! -said Zindzi.":"„Menjünk, olvassunk egy könyvet Oswinnal!” – mondta Zindzi.",
 "Is Oswin your best friend now? -asked Tim Tam":"Most Oswin a legjobb barátod? - kérdezte Tim Tam.",
 "He’s my new friend, -said Zindzi.":"– Ő az új barátom – mondta Zindzi.",
 "He’s your friend too":"Ő is a barátod!",
 "Look, we made you a card":"Nézd, készítettünk neked egy képeslapot.",
 "Should we all play together":"Mindannyian együtt játsszunk?",
 "Let’s all be best friends!":"Legyünk mindannyian legjobb barátok!",
 
 // *** The Cursed Princess elátkozott királykisasszony ***
 // MONDATOK EGYBEN
"There was once a widowed queen who issued a decree that anyone who went ten paces ahead or fell ten paces behind the camp was to be shot dead on the spot.":"Volt egyszer egy özvegy királynő, aki rendeletet adott ki: bárkit, aki tíz lépéssel a tábor előtt haladt, vagy tíz lépéssel lemaradt mögötte, azonnal le kellett lőni.",
"A green dragoon could hold out no longer; finding himself in dire need, he decided to stay behind—regardless of whatever punishment might await him—so he dismounted and remained there for seventy-seven years.":"Egy zöld dragonyos már nem bírta tovább; mivel nagy bajba került, úgy döntött, hogy hátramarad – függetlenül attól, milyen büntetés várhat rá –, ezért leszállt a lováról, és hetvenhét évig ott is maradt.",
"Indeed, the widowed queen, who had marched with her army to strike at the enemy, was so thoroughly defeated that she was even driven out of her own city.":"Csakugyan az özvegy királyné, aki táborával az ellenségre ütött, meggyőzetett oly annyira, hogy még lakó városából is kinyomatott.",
"And the queen had a beautiful daughter; so the queen cast a spell upon the princess and her royal palace, decreeing that no one could reach her without first passing three great trials.":"A királynénak volt egy gyönyörű lánya; varázslattal vette hát körül a hercegnőt és a királyi palotát, és elrendelte, hogy senki sem közelítheti meg a lányt anélkül, hogy előbb három nagy próbát kiállna.",
"After seventy-seven years, the poor dragoon came to his senses and entered the royal city—which lay under a curse—and went into a tavern; he asked for a measure of wine and prepared to pay, for he did indeed have money on him, yet it was the very coin he had received when they first marched off to war, and so it was no longer valid currency.":"Hetvenhét esztendő elteltével a szegény dragonyos észhez tért, bement az átok sújtotta királyi városba, és betért egy fogadóba; bort kért, és fizetni készült – hiszen volt nála pénz –, ám éppen azt az érmét nyújtotta át, amelyet még a háborúba induláskor kapott,",
"The innkeeper told him that the money was no longer accepted in the land, as it bore the image of the queen who had lost her kingdom seventy-seven years prior.":"A fogadós elmondta neki, hogy a pénzt már nem fogadják el az országban, mivel azon annak a királynénak az arcképe szerepelt, aki hetvenhét évvel korábban elveszítette királyságát.",
"The innkeeper explained that the princess—along with the royal seat itself—was under a curse; seeing that the green dragoon was a man of proven mettle—for he had recounted his experiences— the innkeeper suggested he try his luck at breaking the spell.":"A fogadós elmagyarázta, hogy a hercegnő – s vele együtt maga a királyi székhely is – átok alatt áll; látván, hogy a zöldruhás dragonyos bizonyítottan bátor ember – hiszen elmesélte kalandjait –, a fogadós azt tanácsolta neki, próbáljon szerencsét az átok megtörésében.",




// MONDATOK TAGOLVA
"There was once a widowed queen":"Volt egyszer egy özvegy királynő,",
"who had marched with her army to strike at the enemy,":"aki táborával az ellenségre ütött",
"was so utterly defeated that she was driven even from her own dwelling city":"meggyőzetett oly annyira, hogy még lakó városából is kinyomatott.",
"who issued a decree that":"aki rendeletet adott ki:",
"anyone who went ten paces ahead":"bárkit, aki tíz lépéssel a tábor előtt halad",
"or fell ten paces behind the camp was ":"vagy tíz lépéssel lemaradt mögötte, ",
"to be shot dead on the spot":"azonnal le kell lőni.",
"A green dragoon could hold out no longer;":"Egy zöld dragonyos már nem bírta tovább;",
"finding himself in dire need, he decided to stay behind":"mivel nagy bajba került, úgy döntött, hogy hátramarad",
"regardless of whatever punishment might await him":"függetlenül attól, milyen büntetés várhat rá",
"so he dismounted and remained there for seventy-seven years":"ezért leszállt a lováról, és hetvenhét évig ott is maradt",
"Indeed, the widowed queen":"Csakugyan az özvegy királyné,",
"who had marched with her army to strike at the enemy":"aki táborával az ellenségre ütött,",
"was so thoroughly defeated that she was even driven out of her own city":"meggyőzetett oly annyira, hogy még lakó városából is kinyomatott.",
"And the queen had a beautiful daughter;":"A királynénak volt egy gyönyörű lánya;",
"so the queen cast a spell upon the princess and her royal palace,":"varázslattal vette hát körül a hercegnőt és a királyi palotát,",
"decreeing that no one could reach her without":"hogy senki sem közelítheti meg a lányt anélkül,",
"first passing three great trials.":"hogy előbb három nagy próbát kiállna.",

"After seventy-seven years, the poor dragoon came to his senses":"Hetvenhét esztendő elteltével a szegény dragonyos észhez tért,",
"and entered the royal city—which lay under a curse—and went into a tavern;":"bement az átok sújtotta királyi városba, és betért egy fogadóba;",
"he asked for a measure of wine and prepared to pay, for he did indeed have money on him,":"bort kért, és fizetni készült – hiszen volt nála pénz –,",

"yet it was the very coin he had received when they first marched off to war,":"ám éppen azt az érmét nyújtotta át, amelyet még a háborúba induláskor kapott,",
"and so it was no longer valid currency.":"így az már nem volt érvényes fizetőeszköz.",

"The innkeeper told him that the money was no longer accepted in the land,":"A fogadós elmondta neki, hogy a pénzt már nem fogadják el az országban,",
"as it bore the image of the queen who had lost her kingdom seventy-seven years prior.":"mivel azon annak a királynénak az arcképe szerepelt, aki hetvenhét évvel korábban elveszítette királyságát.",

"The innkeeper explained that the princess—along with the royal seat itself—was under a curse;":"A fogadós elmagyarázta, hogy a hercegnő – s vele együtt maga a királyi székhely is – átok alatt áll;",
"seeing that the green dragoon was a man of proven mettle—for he had recounted his experiences—":"látván, hogy a zöldruhás dragonyos bizonyítottan bátor ember – hiszen elmesélte kalandjait –,",
"the innkeeper suggested he try his luck at breaking the spell.":"a fogadós azt tanácsolta neki, próbáljon szerencsét az átok megtörésében.",

 // *** SZAVAK ***
  "widowed":"megözvegyült",
  "coin":"érme, pénzérme, fémpénz",
  "explained":"megmagyarázta",
  "prior":"előzetes",
  "received":"kapott, befogadott",
  "war":"harc, háború, háborúzik",
  "valid":"érvényes",
  "currency":"pénznem, pénz",
  "accepted":"elfogadott",
  "land":"föld, szárazföld",
  "bore":"furat",
  "seat":"ülés",
  "kingdom":"királyság",
  "seeing":"látva, látás",
  "curse":"átok, megátkoz, elátkozás",
  "along":"magával, mentén",
  "luck":"szerencse, véletlen",
  "man":"férfi, ember",
  "proven":"igazolt",
  "mettle":"vérmérséklet",
  "recounted":"elmesélt",
  "experiences":"tudatra ébredés, élmények",
  "innkeeper":"fogadós, kocsmáros",
  "suggested":"javasolt",
  "try":"próbál, kipróbál",
  "breaking":"törés",
  "first":"először, első, legelső",
  "reach":"elér, odaér, felér, feljut, kinyújt, elérés,",
  "decreeing":"elrendelő",
  "beautiful":"csodás, szép, gyönyörű",
  "daughter":"lánya",
  "cast":"vet, dob, szereposztás",
  "upon":"rá, -on -en -ön",
  "spell":"varázslat",
  "princess":"hercegnő",
  "palace":"palota",
  "royal":"királyi",
  "without":"nélkül",
  "half-length":"félalakos",
  "mom":"anya",
  "strike":"csapást mér, strájk",
  "finding":"megállapítás",
  "dire":"szörnyű, irtózatos",
  "await":"vár, várakozik",
  "punishment":"büntetés, fenyítés",
  "stay":"marad, tartózkodik, időzés",
  "decided":"határozott, elszánt",
  "regardless":"tekintet nélkül, kíméletlen",
  "dismounted":"leszállt",
  "remained":"megmaradt, maradt",
  "seventy":"hetven",
  "seven":"hét",
  "seventy-seven":"hetvenhét",
  "years":"évek",
  "army":"hadsereg, sereg",
  "marched":"menetelt",
  "enemy":"ellenség",
  "driven":"űzött, hajtott",
  "defeated":"legyőzött",
  "thoroughly":"alaposan",
  "hold":"feltart, várakoztatás, fog",
  "no longer":"már nem",
  "longer":"hosszabb",
  "dragoon":"dragonyos",
  "decree":"rendelet, határozat",
  "anyone":"bárki, valaki",
  "queen":"királynő, királyné",
  "issued":"kiadott",
  "paces":"lépések",
  "dead":"halott",
  "camp":"tábor",
  "ten":"tíz",
  "widowe":"özvegy",
  "went":"ment",
  "about":"-ról -ről, miatt, körülbelül",
  "three":"három",
  "hopscotch":"ugróiskola",
  "Let’s":"gyerünk",
  "Okay":"rendben",
  "Should":"kellene",
  "made":"készített, csinált",
  "He’s":"ő, ő az (férfi)",
  "He is":"ő, ő az (férfi)",
  "read":"olvas, elolvas, leolvas",
  "Monday":"hétfő",
  "on Monday":"hétfőn",
  "rode":"lovagolt",
  "scooters":"robogók",
  "scooter":"roller, robogó",
  "played":"játszott",
  "card":"kártya, igazolvány",
  "done":"kész",
  "convenience":"kényelem, megfelelés",
  "I’ll":"fogok",
  "doing":"csinálás, tett",
  "puzzle":"rejvény, kirakós",
  "I will":"fogok",
  "thank you":"köszönöm",
  "thank":"köszönet, köszönetet mond",
  "together":"együtt, közösen",
  "keep books":"könyvel",
  "excuse me":"elnézést",
  "meet":"találkozik, találkozó, összeül, megismer",
  "meeting":"találkozás, gyűlés",
  "sorry":"bocsánat, sajnálat, sajnálom",
  "I am sorry":"sajnálom",
  "I'm sorry":"sajnálom",
  "I sorry":"sajnálom",
  "I have been seeing":"láttam, találkozgatok valakivel",
  "I was":"voltam",
  "I was seeing":"láttam / találkozgattam valakivel",
  "were you":"te voltál?",
  "weren't":"nem voltak",
  "were not":"nem voltak",
  "it is":"ez, az -van (dolog)",
  "she is":"ő, ő az, ő van(nő)",
  "he is":"ő, ő az, ő van(férfi)",
  "you're":"te vagy",
  "you are":"te vagy",
  "many":"sok, számos",
  "know":"tud, ismer, ért valamihez",
  "condescending":"leereszkedő",
  "trite":"elcsépelt",
  "astraight":"egyenes",
  "never":"soha, sohasem",
  "gall":"epe",
  "jaded":"elcsigázott, fáradt, megcsömörlött",
  "belong":"tartozik, tartozik valakihez, valamihez, valakié",
  "us":"minket, nekünk, bennünket",
  "lose":"veszít, elveszít, elveszteget, vereséget szenved",
  "'cause":"ok, okoz, előidéz",
  "destiny":"sors, végzet",
  "pick":"csákány, csipked, fogvájó",
  "fight":"harc, harcol, verekszik",
  "powers":"hatalmak, erők",
  "song":"dal, ének",
  "élet":"élet",
  "ain't":"nem, nem vagyok",
  "we'll":"fogunk",
  "we will":"fogunk",
  "we will see":"meglátjuk",
  "we'll see":"meglátjuk",
  "period":"időszak, időtartam",
  "choose":"választ, kiválszt",
  "got":"kapott, vált valamilyenné",
  "We've":"nekünk van, voltunk",
  "anymore":"többé",
  "viewing":"megtekintés",
  "sightings":"észlelések",
  "optimum":"optimális, legjobb, legkedvezőbb",
  "above":"fent, felül, fölé",
  "gonna":"fogok",
  "against":"ellen, ellenében, szemben,",
  "contrasts":"kontrasztok",
  "reflects":"tükröz",
  "sky":"ég, égbolt",
  "darker":"sötétebb",
  "amount":"összeg",
  "full":"tele, teli",
  "crossing":"átkelés, keresztezés",
  "Earth’s":"A Föld",
  "horizon":"horizont, látóhatár",
  "boxwoods":"buxus",
  "hostas":"hosták (ázsiai növény)",
  "rain":"eső",
  "kitten":"cica, kismacska",
  "thorn":"tüske",
  "pain":"fájdalom",
  "check":"ellenőriz, csekk, sakkban tart, sakkot ad",
  "homes":"otthonok",
  "spay":"ivartalanít",
  "new":"új",
  "vet":"állatorvos",
  "cozied":"meghitt",
  "grown":"növekedett, felnőtt, megnőtt",
  "asleep":"alvó",
  "snug":"meghitt",
  "bellies":"hasak",
  "peep":"kukucskál, kukucskálás",
  "rest":"pihenés, pihen",
  "safe":"biztonságos, páncélszekrény, veszélytelen, páncélfiók, széf",
  "family":"család",
  "crew":"legénység",
  "settled":"rendezett",
  "calmed":"megnyugodott",
  "freed":"felszabadított, megszabadított",
  "carefully":"gondosan",
  "saw":"(I / you / he / she / we / they - saw) = lát múlt ideje/, a saw, The saw = egy fűrész, A fűrész",
  "underground":"földalatti, föld alatti, metró",
  "corner":"salok, szöglet, zug",
  "tram":"villamos",
  "course":"tanfolyam, kurzus, kúra",
  "left":"bal, baloldali, balkéz, balfelöli, otthagyott",
  "bus":"busz, gyűtősín",
  "across":"keresztbe, keresztben",
  "cross":"kereszt, keresztez",
  "ahead":"előre",
  "could":"tudott",
  "could you":" meg tudnád",
  "straight":"egyenes, egyenesen",
  "I'd":"én -nák -nék",
  "of course":"természetesen",
  "please":"kérem, örömöt szerez, tetszik vkinek,kedvére tesz vkinek",
  "can":"tud, képes",
  "excuse":"elnézést, menteget",
  "bedroom":"hálószoba",
  "floor":"padló, parketta, padlózat, emelet",
  "daffodil-covered":"nárciszokkal borított",
  "armchair":"karosszék, fotel",
  "daffodil":"nárcisz",
  "covered":"fedett, borított",
  "flip":"átfordít",
  "flop":"leesik, lepottyan",
  "groaned":"nyögött, felnyögött",
  "staggering":"tántorgó, megdöbbent, megdöbbentő",
  "softly":"enyhén, halkan",
  "floated":"lebegett",
  "fine":"finom, megbírságol, bírság",
  "away":"el, messzire",
  "others":"mások, egyebek",
  "gasped":"felsóhajtott, sóhatott",
  "thinking":"gondolkodás",
  "several":"számos",
  "either":"bármelyik",
  "think":"gondol",
  "comb":"fésű",
  "strands":"szálak",
  "strand":"szál",
  "fairly":"meglehetősen, méltányosan, korrektül, elfogadhatóan",
  "plans":"tervek",
  "hummed":"dúdolt",
  "level":"szint, szintvonal, szintez",
  "energy":"energia",
  "euphoria":"euforia, jó közérzet",
  "excitement":"izgalom, izgatottság",
  "personal":"személyes",
  "one’s":"valakié",
  "everything":"minden",
  "year":"év",
  "depending":"függően",
  "weeks":"hetek",
  "week":"hét",
  "nothing":"semmi",
  "7":"hét",
  "glorious":"dicső",
  "approached":"megközelített",
  "forward":"előre, előrehaladó, előre irányul",
  "vac":"vakáció",
  "ever-mounting":"folyamatosan növekvő",
  "looked":"nézett",
  "Nigerian":"Nigériai",
  "school-free":"iskolamentes",
  "Kid’s":"gyerekek",
  "every":"minden, mind",
  "country":"ország",
  "height":"magasság, magaslat, csúcspont",
  "high":"magas, magasan",
  "kids":"gyerekek",
  "vacation":"vakáció",
  "holidays":"szünetek, szabadságok, munkaszüneti napok",
  "holiday":"szünet, szabadság, munkaszüneti nap",
  "reason":"ok, fejteget",
  "air":"levegő, légi-, szelőzik",
  "touch":"megérint, tapint, tapintás, nyúl",
  "palpable":"kézzelfogható, érezhető",
  "looks":"kinézet",
  "almost":"majdnem, csaknem",
  "city":"város",
  "estate":"birtok",
  "residential":"lakó, tartózkodási",
  "streets":"utcák",
  "street":"utca",
  "child":"gyemek, gyerek",
  "children":"gyermekek, gyerekek",
  "play":"játék, játszik",
  "playing":"játszás",
  "birds":"madarak",
  "bird":"madár",
  "birdie":"kismadár",
  "happily":"boldogan",
  "singing":"éneklő, éneklés",
  "blaze":"lángol",
  "blazed":"lángolt",
  "anything":"bármi",
  "feel":"érezni, érez, tapint",
  "worst":"legrosszabb, legrosszabbul",
  "absolutely":"feltétlenül, teljesen",
  "wants":"akar",
  "want":"akar",
  "always":"mindig, örökké",
  "though":"bár, ugyan, mégis, habár",
  "hers":"övé, az övé, (a(z) ő -ja -je)",
  "opined":"véleményt nyilvánított",
  "fan":"legyez, hűsít, legyező, szellőző",
  "teacher":"tanár(nő), tanító(nő)",
  "'s":"-é, ezé, azé, valakinek(-minek a tulajdona, része",
  "such":"ilyen, olyan, hasonló",
  "school":"iskola",
  "wasn’t":"nem volt",
  "facial":"arápolás, arckozmetika",
  "pride":"büszkélkedik, büszkeség, gőg, önérzet",
  "prideful":"kevély, büszke",
  "indulgent":"elnéző",
  "shaking":"rázás, remegő",
  "termed":"nevezett",
  "feature":"jellemző, vonás, arcvonás, valamilyen jelleget kölcsönöz",
  "most":"legtöbb, leg...-bb, leg-",
  "visible":"látható",
  "everyone":"mindenki, valamennyien",
  "face":"arc, számlap, szembenéz",
  "pretty":"csinos, szép",
  "decidedly":"határozottan",
  "upturned":"felfelé fordított",
  "adorning":"díszítő",
  "perky":"csintalan",
  "slightly":"némileg, sértően",
  "age":"kor, életkor, öregít",
  "tall":"magas",
  "beach":"strand, tengerpart",
  "beaches":"strandok",
  "spent":"költött",
  "skin":"bőr, megnyúz",
  "pubescent":"serdülő",
  "female":"nő, női",
  "awry":"félrecsapott, félrecsapva",
  "wispy":"sovány",
  "hair":"haj, hajszál",
  "mommy":"anyuka",
  "walking":"séta, gyalogló, gyaloglás",
  "mind":"elme, ész",
  "happening":"esemény",
  "totally":"teljesen",
  "bear":"medve, kibír, elvisel, hordoz, elszenved, mogorva ember",
  "thing":"dolog",
  "things":"dolgok",
  "nose":"orr, kiszaglász, megérzi a szagát",
  "alarmed":"megrémült",
  "however":"viszont, bármennyire, bárhogyan, akárhogyan",
  "moment":"pillanat",
  "month":"hónap",
  "image":"kép",
  "wide":"széles, tág",
  "reflection":"tükörkép, visszaverődés",
  "unthinkable":"elképzelhetetlen",
  "money":"pénz",
  "quite":"egészen",
  "pocket":"zseb, zsebre tesz, zsebre vág",
  "vanished":"eltűnt",
  "herself":"önmaga, ő maga, őt magát (nő)",
  "himself":"önmaga, ő maga, őt magát (férfi)",
  "itself":"maga (semleges)",
  "glimpse":"pillantás, futó pillantás, pislákoló fény",
  "caught":"elkapott",
  "smile":"mosoly, mosolyog",
  "better":"jobb, jobban, különb, különbül",
  "much":"sok, sokkal",
  "speechless":"szótlan",
  "astonishment":"csodálkozás",
  "cover":"borító, fedezék, takaró, címlap, lefedés, lefed",
  "clearl":"világos, tiszta",
  "stone":"kő",
  "gaped":"tátott szájjal bámult",
  "stones":"kövek",
  "carved":"faragott",
  "seemed":"úgy tűnt",
  "awful":"szörnyű, rettenetes",
  "hands":"kezek","hand":"kéz, kézi",
  "another":"másik, még egy",
  "sister":"nővér, lány testvér",
  "fell":"esett",
  "palm":"tenyér, marok",
  "jump":"ugrik, ugrás, ugrat",
  "feet":"lábak",
  "foot":"láb",
  "measure":"intézkedés, felbecsül, felmér, rendszabály",
  "smacking":"csattogó",
  "two":"két, kettő",
  "making":"készítés",
  "planet":"bolygó",
  "kid":"kölyök, kisgyerek",
  "book":"könyv",
  "people":"emberek, nép",
  "added":"hozzáadva",
  "world":"világ",
  "didn’t":"nem",
  "visitors":"látogatók",
  "visitor":"látogató",
  "picture":"kép",
  "sort":"rendez, fajta",
  "Aliens":"idegenek",
  "facing":"szembenézve, szembenézés",
  "Alien":"idegen",
  "page":"oldal, lap könyvben, apród",
  "don’t":"ne, nem",
  "believe":"hisz, vél",
  "occur":"előfordul, megesik",
  "before":"előtt, mielőtt, azelőtt, előbb, inkább",
  "sunrise":"napkelte",
  "sunset":"napnyugta",
  "or":"vagy",
  "hours":"órák",
  "hour":"óra",
  "summer night":"nyári éjszaka",
  "within":"belül, benn",
  "few":"kevés, nem sok, néhány",
  "twins":"ikrek",
  "wick":"kanóc, lámpabél",
  "dog":"kutya, eb",
  "do":"csinál, tesz, cselekszik, megcsinál (segéd ige)",
  "local":"helyi,helybeli",
  "preferred":"előnyben részesített",
  "location":"helyzet, elhelyezkedés, földrajzi fekvés",
  "user’s":"felhasználóé",
  "zone":"zóna, övezet, terület, égöv",
  "begin":"kezd, kezdődik",
  "Station":"állomás, állomásoztat",
  "will":"akar, akarat, szándék, végrendelet, végrendelkezik",
  "opportunity":"lehetőség, alkalmas idő, alkalomszerűség",
  "sighting":"irányzék",
  "Space":"tér, hely, űr",
  "spot":"hely, folt, anyajegy, meglát",
  "International":"nemzetközi",
  "scattered":"elszórt",
  "sharp":"éles",
  "home":"otthon, itthon, haza",
  "prickly":"tüskés",
  "burrs":"sorja",
  "into":"-ba, bele",
  "some":"néhány, némely,valami, mintegy, nemi",
  "glass":"üveg, pohár, beüvegez, ablaktábla",
  "scatter":"szétszór, elterjeszt, kiszór",
  "started":"elundult, elkezdődött",
  "looking":"néz",
  "faced":"szembesült",
  "instead":"helyette",
  "scram":"elsiet",
  "highway":"országút, autóút, főút",
  "cars":"autók",
  "car":"autó, gépkocsi",
  "fast":"gyors, gyorsan, böjtöl, koplal",
  "blinding":"vakító",
  "headlights":"fényszórók",
  "Headlight":"fényszóró, reflektor",
  "turned":"fordult",
  "turn":"fordulat, fordul, kanyrodik",
  "start":"indul, kezdődik,kezdet",
  "blared":"harsogott",
  "blare":"harsog",
  "horn":"kürt, duda, szarv",
  "tires":"gumiabroncsok",
  "tire":"gumi, autógumi",
  "take":"vesz, visz, fog, telik",
  "be":"lenni, van, létezik",
  "stepped":"lépett",
  "they":"ők, azok",
  "oak":"tölgy",
  "dread":"retteg",
  "overhead":"felső, felül",
  "whipped":"felvert",
  "desperate":"kétségbeesett",
  "white":"fehér, sápadt",
  "heart":"szív",
  "other":"más, másik",
  "staring":"bámulás, bámészkodás",
  "moaned":"nyögött, (sóhajtott)",
  "each":"minden",
  "clung":"ragaszkodott",
  "trying":"próbálkozás",
  "cries":"sírások, kiáltások",
  "beneath":"alatt, alul, lenn",
  "shrill":"éles, metsző, sikít, visít",
  "skies":"égbolt",
  "stormy":"viharos",
  "put":"tesz, helyez, rak",
  "below":"alatt, alá, alul",
  "pointing":"mutatás",
  "tight":"szoros, szorosan",
  "holding":"megtartás, tárolás, megfogás",
  "hurried":"sietős",
  "coats":"kabátok",
  "coat":"kabát, bevonat, beken",
  "steps":"lépések",
  "our":"mienk, miénk -unk -nk -jaink",
  "save":"megment, spórol, megtakarítás",
  "battled":"küzdött",
  "step":"lépés, lép, lábnyom",
  "scooping":"mérés",
  "porch":"veranda",
  "storm":"vihar",
  "kittens":"kiscicák",
  "hide":"rejtőzik, elrejt, eldug",
  "acted":"cselekedett",
  "distressed":"szomorú",
  "Raindrops":"esőcseppek",
  "ground":"terület, talaj, föld",
  "paced":"tempójú",
  "pelted":"záporozott",
  "West":"nyugat",
  "if":"ha, feltéve, azonban",
  "wondered":"azon tűnődött",
  "pan":"lábas, sepenyő",
  "lingered":"időzött",
  "invited":"meghívott, behívott, hívott (be -ki)",
  "friendly":"barátságos",
  "meows":"nyávog",
  "sang":"énekelt",
  "gulping":"habzsolva nyelés",
  "After":"azután, utána, későbbi",
  "chow":"ebéd",
  "milk":"tej",
  "fresh":"friss",
  "filled":"megtöltött",
  "fill":"feltölt, kitölt, megteleik",
  "scratches":"karcolások",
  "use":"használ, alkalmaz, felhasznál",
  "scratch":"karcol, karmol, karmolás",
  "heal":"gyógyít",
  "cuts":"vágások",
  "cut":"vágott, vág, lenyír",
  "has":"van neki",
  "meal":"étel, étkezés",
  "time":"idő, alkalom, időpont -szor -szer -ször",
  "needs":"igények, szükségletek",
  "need":"igény, szükséglet, megkíván",
  "cared":"törődött",
  "care":"gondoskodás, törődés, gondoz, aggodalom",
  "for":"számára, miatt, helyett, -ért -ra -re",
  "been":"volt",
  "has been":"volt",
  "thin":"vékony, sovány, vézna",
  "frail":"törékeny, gyenge",
  "hunkered":"guggolt",
  "mat":"lábtörlő, szőnyeg",
  "tell":"elmond",
  "had":"volt",
  "again":"újra",
  "curled":"göndör",
  "came":"jött",
  "green":"zöld",
  "hoped":"remélt",
  "hope":"remény, remél",
  "come":"jön",
  "surprised":"meglepődött",
  "back":"vissza",
  "thought":"gondolat",
  "my":"az én -m -am -em -om -öm",
  "hunt":"vadászat, vadászik, üldöz",
  "sight":"látás, meglát, látóképesség",
  "cat":"macska",
  "hunted":"vadászott, üdözött",
  "leaped":"ugrott",
  "perch":"kakasülő, bak",
  "leape":"ugrás",
  "graceful":"könnyed",
  "scared":"rémült, megrémült",
  "scare":"megijeszt, ijedelem, megrémít",
  "uneasy":"kényelmetlen",
  "see":"lát, megnéz, látni",
  "feeling":"érzelem, érzés",
  "stared":"meresztette a szemét",
  "locked":"bezárt, zárt",
  "sun":"nap",
  "woodpile":"farakás",
  "enough":"elég, eléggé",
  "passed":"átment",
  "pass":"átmegy",
  "shadows":"árnyékok",
  "shadow":"árnyék",
  "shadowing":"árnyékolás",
  "backdoor":"hátsó ajtó",
  "flew":"repült",
  "right":"jobb, jobbra",
  "next":"következő, legközelebbi, ezt követően, azután",
  "dart":"dárda",
  "head":"fej",
  "poked":"megbökött",
  "poke":"bökés",
  "when":"amikor, mikor",
  "have":"van",
  "creature":"teremtmény, lény",
  "mystery":"rejtély",
  "late":"késő, későn",
  "is":"van",
  "off":"el, félre",
  "shot":"lövés, rúgás",
  "it":"az (dolog, állat)",
  "around":"körbe, körül",
  "whatever":"bármi, akármi, mindenesetre",
  "gazed":"meredt",
  "remembered":"emlékezett",
  "remember":"emlékezik",
  "eye":"szem",
  "fascinating":"elbűvölő",
  "hopefully":"remélhető, remélhetőleg",
  "shoulder":"váll, vállára vesz,)",
  "look":"tekintet, nézés, néz",
  "Like":"tetszik, mint, ahogy, hasonló, ahogy, kedvel, ugyanolyan",
  "instance":"példány",
  "sneaking":"alatomos",
  "low":"alacsony,(halk)",
  "low, wobbly voice":"halk, remegő hang",
  "blink":"pislogás",
  "it's terrible":"Borzalmas",
  "yelled":"kiabált",
  "earth":"föld",
  "didn't blink":"meg sem rezzent",
  "rubbing":"dörzsöl, dörzsölés",
  "upper":"felső",
  "lip":"ajak",
  "lips":"ajkak",
  "finger":"ujj, tapint, megtapint",
  "really":"igazán, valóban",
  "dreadful":"szőrnyű, félelmetes",
  "absentmindedly":"szórakozottan",
  "in front of":"előtt",
  "eyes":"szemek", 
  "eye":"szem",
  "page facing":"szemközti oldal",
  "funny":"vicces, mulatságos",
  "muttered":"morgolódott",
  "wobbly":"roskatag, remegő, ingó", 
  "voice":"hang",
  "behind":"mögött, mögé, hátra, hátul",
  "her":"őt(nő), neki(nő), övé",
  "only":"csak, egyedüli, csupán, hanem, azonban",
  "bed":"ágy, beágyaz",
  "room":"szoba, férőhely, szobát kiad, szállásol",
  "did":"tett (csinált -vmit)",
  "react":"reagál",
  "half":"fél, félig, felez, befejezetlen",
  "length":"hosszú, hossz, hosszúság",
  "mirror":"tükör",
  "front":"elülső, előre",
  "halfway":"félúton",
  "clearly":"egyértelmű, érthető, tisztán",
  "lying":"fekvő",
  "pillows":"párnák",
  "pillow":"párna, vánkos",
  "leave":"hagy, elhagy, elmegy, otthagy",
  "even":"még",
  "nocturnal":"éjszakai",
  "out":"ki, kinn, külső, kifelé",
  "Maybe":"talán, esetleg, lehetséges",
  "something":"valami",
  "prowl":"olálkodik, kószál, portyázás",
  "called":"hívott",
  "call":"hív",
  "summer":"nyár, nyári",
  "warm":"meleg, melegít, felhevít",
  "more":"több, nagyobb, inkább",
  "I saw":"láttam",
  "red":"vörös, piros",
  "had I seen":"láttam volna",
  "possom":"oposszum",
  "an":"egy", 
  "owl":"bagoly",
  "I ran":"futottam",
  "bushes":"bokrok",
  "bush":"bokor",
  "apart":"külön, széjjel",
  "yanked":"megrántotta",
  "them":"őket, azokat, nekik",
  "I could":"tehetném",
  "Good afternoon":"Jó napot.",
  "not":"nem",
  "sure":"persze, igazán, biztos, kétségtelen",
  "crept":"lopódzott",
  "the little dog":"a kiskutya",
  "from":"-ból -ből -tól -től -ról -ről",
  "sounds of the squall":"vihar hangjai",
  "squall":"szélroham",
  "sound":"hang",
  "sounds":"hangok",
  "down":"le-, lefelé",
  "hall":"előszoba, csarnok",
  "shook":"megrázta",
  "dashed up":"felrohant",
  "stairs":"lépcső",
  "gloomy":"komor",
  "thunder":"mennydörgés",
  "over":"felett, át, fölé, felül",
  "moon":"hold",
  "flashed":"felvillant",
  "lightning":"villám, villámlás",
  "lightning bolts":"villámcsapások",
  "blew":"fújt",
  "cloud":"felhő, felleg, felhőzet",
  "clouds":"felhők",
  "wicked":"gonosz",
  "old":"rédi, öreg, koros",
  "tore":"széttépett",
  "tore down":"lebontott, letörött",
  "limbs":"ágak, végtagok",
  "ripped":"izmos, kidolgozott",
  "through":"keresztül, át",
  "trees":"fák",
  "tree":"fa",
  "wind":"szél",
  "winds":"szelek",
  "just":"éppen, csak, egyszerűen",
  "outside":"odakinn, kívül, külső, szabadban",
  "bye":"Viszlát",
  "welcome":"Üdvözöljük! Üdvözölöm!",
  "how": "hogy, hogyan, mennyire, miként",
  "evening": "este",
  "night":"éjszaka",
  "are you": "te vagy?",
  "afternoon":"délután",
  "morning" : "reggel",
  "hello" : "helló",
  "hi" : "szia",
  "yes" : "igen",
  "me" : "nekem, engem",
  "i'm" : "én vagyok, vagyok",
  "i" : "én",
  "i am": "én vagyok, vagyok",
  "what is": "mi a",
  "what's" : "mi a",
  "name": "név elnevezés",
  "phone": "telefon",
  "your": "tied, tiéd, öné, tietek, önöké (Névmás)",
  "number":"szám",
  "what":"mi",
  "Are you on the phone?": "Telefonálsz?",
  "Good bye.":"Viszlát.",
  "How are you?":"Hogy vagy?",
  "Good evening.":"Jó estét.",
  "How do you do?":"Örvendek! Üdvözlöm! (indulatszó)",
  "Good night.":"Jó éjszakát.",
  "Yes, I’m on the phone.":"Igen, telefonálok.",
  " what is your name?":"Mi a neved? Hogy hívnak?",
  "Good morning.":"Jó reggelt!",
  "What’s your phone number?": "Mi a telefon számod?",
  "on the phone": "telefonon",
  "are": "segéd ige (van, vannak)",
  "brave": "bátor",
  "fox": "róka",
  "hungry": "éhes",
  "forest": "erdő",
  "flour": "liszt",
  "eggs": "tojás",
  "slowly": "lassan",
  "bake": "sütni",
  "twenty": "húsz",
  "edge" : "él, éle, szél, széle",
  "far" : "messze, távol",
  "winding": "tekercselés, kanyargós,csavarás",
  "long": "hosszú",
  "on": "on, -en, -ön, -ra, -re",
  "town":"város",
  "woods":"erdő",
  "in": "-ban, -ben, -ba, -be",
  "thick": "vastag, széles, (sűrű)",
  "curved":"ívelt",
  "road": "út",
  "where": "hol, hová, ahova, (ahol)",
  "tiny": "apró",
  "house": "ház",
  "stood": "állt",
  "a" : "egy",
  "the": "a, az (névelő)",
  "sat": "ült",
  "who": "ki, kik, kicsoda, aki, akik",
  "was": "volt",
  "sad": "szomorú, bánatos, bús",
  "all": "teljesen, minden, valamennyi, összes, összesen mindegyik",
  "alone": "egyedül",
  "there": "ott, oda, amott",
  "no": "nem, nincs, semmilyen, semmiféle",
  "one": "egy, egyik, ember, valaki",
  "there was no one": "Nem volt senki",
  "to play": "játszani",
  "with no friends": "barátok nélkül",
  "was sad": "szomorú volt",
  "no one": "senki",
  "then": "akkor, majd, azután",
  "he": "ő (férfi, fiú, hímnemü)",
  "she":"ő (nő, lány, nőnemű)",
  "with no friends to be had": "barátok nélkül",
  "to be had": "elérhető, megszerezhető",
  "while": "miközben, mialatt, (amíg)",
  "waited": "várt",
  "wait": "vár, várakozik, várás",
  "and":"és, meg",
  "watched": "figyelt, (nézett)",
  "he watched": "figyelt",
  "he waited": "várakozott, várt",
  "for the":"arra, (számára, neki)",
  "door to unlock": "ajtó kinyitása, ajtó kinyitására, ajtó nyitására)",
  "it grew": "növekedett, nőtt",
  "dark": "sötét, sötétség",
  "in the house": "a házban",
  "heard":"hallott",
  "loud": "zaj, hang",
  "those":"azok, azokat",
  "you" : "te, ön, téged, maga, ti, titeket", 
  "raccoon":"mosómedve",
  "chased":"üldözött",
  "chase":"üldöz, vadászik, elkerget",
  "path":"útvonal, ösvény", 
  "mean":"jelent, átlag, szándékozik",
  "by":"mellett, -nál -nél -ra -re -val -vel",
  "to go":"menni",
  "to":"-hoz -hez -höz -ba -be -ig",
  "go":"megy, halad",
  "danger":"veszély",
  "too":"is, túlságosan, nagyon",
  "soon":"hamar, nemsokára",
  "too soon":"túl korán",
  "coming out":"kiért, kijött",
  "coming":"eljövetel, érkező, közeledő",
  "howled":"üvöltött",
  "whimpered":"nyüszített",
  "terrible":"borzasztó",
  "fear":"fél, félelem, retteg, aggódás",
  "would":"lenne, tudott",
  "rescue":"mentés, megment, kiszabadítás",
  "puppy":"kölyökkutya",
  "food":"étel, élelem, élelmiszer",
  "day":"nap, nappal",
  "became":"vált, lett valami, vált valamivé",
  "daytime":"nappal",
  "once":"egyszer, valaha",
  "more":"több, nagyobb, inkább",
  "once more":"még egyszer",
  "but":"de, azonban, csak, csupán kivéve",
  "poor":"szegény",
  "lonesome":"magányos",
  "pup":"kiskutya, kölyökkutya",
  "couldn't":"nem tudott",
  "any":"bármilyen, valamilyen, valami, valamennyire, valamivel",
  "any more":"többé",
  "so":"így, úgy, úgyhogy,tehát, olyan, ilyen",
  "clawed":"karom",
  "at":"-nál -nél -kor, -on -en -ön -ban",
  "windows":"ablakok","window":"ablak",
  "pawed":"mancsával",
  "pawe":"mancs",
  "doors":"ajtók",
  "door":"ajtó",
  "pushed":"nyomott, megnyomott",
  "push":"nyom, taszít, lök, tol, előretörés",
  "scratched":"karcolt, kapart",
  "screen":"képernyő, ellenző, rács",
  "hole ‘til":"egészen addig, amíg",
  "twisted":"sodrott, megpördült",
  "shoved":"lökött",
  "squeezed":"összenyomott",
  "his":"övé -neki (férfi)",
  "way":"út, mód, irány, távolság",
  "free":"szabad, ingyenes, kötetlen, fesztelen",
  "now":"most, jelenleg, azonnal",
  "last":"utolsó, végső, eltart, tart, legutoljára",
  "very":"nagyon, ugyanez",
  "slow":"lassú",
  "found":"talált",
  "of":"-ból -ből -nak a -nek a",
  "fur":"szörme, prém",
  "toes":"lábujjak",
  "stuck":"megragadt, beszorult",
  "legs":"lábak",
  "his legs":"a lábai",
  "as":"mint, mivel, ahogyan, akár, amennyire",
  "ran":"futott",
  "run":"fut",
  "running":"futás, szaladás",
  "field":"mező, rét, pálya",
  "that":"az, annyira, azt",
  "this":"ez, ezt",
  "lost":"elveszett",
  "little":"kicsi, kis",
  "hurt":"fáj, megsérült",
  "are you hurt?":"megsérültél?",
  "Let":"hadd",
  "let me":"hadd",
  "get":"megkap, válik, elér, hozzájut, kerül valahova",
  "inside":"belső, belül",
  "froze":"fagyott, megfagyott, fázott",
  "glad":"boldog, örül",
  "happy":"boldog, örül",
  "rescued":"megmentett, kimentett, mentett",
  "find":"talál, megtalál, rátalál",
  "friend":"barát",
  "could":"tudott",
  "help":"segítség, segít",
  "him":"ő -neki, őt, ő -hozzá",
  "someone":"valaki",
  "kind":"fajta, kedves, jóindulatú",
  "loved":"szeretett, szerette",
  "first":"első, először, elsőként",
  "ride":"lovaglás, autózás, utazás járművel",
  "car":"autó, gépkocsi",
  "buddy":"haver, pajtás, cimbora",
  "get up!":"kelj fel",
  "here":"itt, ide",
  "up":"fel, felfelé, feláll, fenn, emel",
  "we":"mi",
  "screeched":"sikított",
  "said":"mondott, mondta",
  "lady":"hölgy",
  "'til":"amíg",
  "here we are":"itt vagyunk, megérkeztünk",
  "buddy, get up!":"pajti kelj fel!",
  "quickly":"gyorsan",
  "stopped":"megállt",
  "opened":"kinyitott",
  "possibly":"esetleg, talán",
  "take anymore":"többet elviselni",
  "Could he possibly take anymore?":"Vajon képes lenne még többet elviselni?",
  "cried":"kiáltott fel",
  "Buddy, get up! Here we are!":"Pajti kelj fel megérkeztünk!",
  "hole":"lyuk, kilyukaszt, rés, átfúr",
  "kept":"tartotta",
  "might":"hatalom",
  "were":"voltak",
  "best":"legjobb",
  "friend":"barát",
  "friends":"barátok",
  "asked":"kérdezte",
  "ask":"kérdez, megkér, felkér",
  "play":"játszik",
  "dress-up?":"jelmezes öltözködés",
  "with":"-val -vel -nál -nél noha, ",
  "-get well soon-":"Jobbulást kívánok!"
};
